# Generated by Django 5.1.7 on 2025-06-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_celery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
