# Generated by Django 5.2.3 on 2025-07-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_celery_app', '0004_author_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='subject',
            new_name='bio',
        ),
    ]
