# Generated by Django 5.2.3 on 2025-07-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_celery_app', '0005_rename_subject_author_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
